### PR TITLE
RFC: Ltac2

### PR DESCRIPTION
**Pull request by gares**
Submitted in place of @ppedrot (feel free to take over this PR)

### CODE REVIEW

**Comment by herbelin** [comment]
It seemed to me that there is already very cool and useful significant creative work done about Ltac2. Naive question: would it make sense to already integrate some parts of it, including datatypes and typing, with, maybe some hooks to reuse missing primitives from Ltac?

**Comment by gares** [comment]
Maybe the title was misleading (fixed now) but this PR is really about the Ltac2 CEP.

**Comment by Zimmi48** [comment]
Should this get merged? Closed?

**Comment by ppedrot** [comment]
I think the standard course is to merge it, but it's kind of a duplicate with the Ltac2 documentation.

**Comment by Zimmi48** [comment]
CEPs are snapshots of a design document at one point in time, whereas the documentation will evolve with the code.

**Pull request merged**
