### PR TITLE
RFC: Representation of return predicate and branches of "match" in the implementation, and how reduction tactics should treat them.

### PR DESCRIPTION
**Pull request by herbelin**
Rendered [here](https://github.com/herbelin/ceps/blob/reduction-in-inductive-predicate-and-branches/text/inductive-branch-predicate-representation-and-reduction.md).

### CODE REVIEW

**Comment by gares** [comment]
The CEP template file proposes a model with sections (in a specific order).
Why didn't you follow it?

**Comment by herbelin** [comment]
The first reason is that I did not remember that there was a model. What would you like me to change in what I did? Would you like another order of sections?

**Comment by herbelin** [comment]
@gares: I added a "TD;LR" section, assuming that this is what you felt was missing.

**Comment by maximedenes** [comment]
> The CEP template file proposes a model with sections (in a specific order).
> Why didn't you follow it?

@gares is that a PR template? If not, it should be turned into one.

**Comment by mattam82** [comment]
I like the idea of having a canonical representation. For example, CertiCoq has a phase to go into the (Δ, brs) style for pattern matching branches, avoiding dummy beta-reductions at run-time, but tha phase creates dummy β-η redexes to be removed later by another phase, which is a pity (but it's not too bothersome either). I just had not anticipated this problem because the encoding of branches was not clear to me at first (always η-expanded or not in particular). My only worry is that much code does its own Array.map foo brs on branches currently, but maybe I'm overestimating that. I think the part about let is a bit orthogonal here, no?

**Comment by herbelin** [comment]
> My only worry is that much code does its own Array.map foo brs on branches currently, but maybe I'm overestimating that. 

I already started to develop a library of combinators to replace these `Array.map` by some kind-of `map_branches`. So, I could almost propose something in the next few days.

> I think the part about let is a bit orthogonal here, no?

Yes and no. Yes, in that we can adopt a canonical representation without the lets. No, in that we have to make a decision wrt lets in adopting a canonical representation. Or maybe I don't get what you mean by "let" is orthogonal.

**Comment by gares** [comment]
> @gares is that a PR template? If not, it should be turned into one.

At the root of the repo there are 2 file, a README and a file called 000-template that is also mentioned in CEP0... If you know how to, please turn it into a template.

In any case my point was : please make the motivation clear. I think @herbelin added this section in his second commit.

**Comment by Zimmi48** [comment]
It can't really been turned into a PR template because PR template are for the PR description, not the PR content.

**Comment by herbelin** [comment]
Hi, I'm progressively implementing this ceps in a private branch. The current state is the following:
- `lazy`, `cbv`, `cbn` now see branches of a `match` as part of the structure of a `match`
  - in particular, binding arguments of the constructor to the pattern variables is now pure `match` reduction and does not require the  `beta` flag anymore (for instance `Eval lazy match in match 2 with 2 => 1 | _ => 0 end` now reduces to `1` without needing `beta`)
  - similarly,  `lazy`, `cbv`, `cbn` do not contract anymore the `let`s which are parts of the signature of a constructor (see coq/coq#7068)
- I started to make branch and predicate combinators for `map` but not yet for `fold` and `iter` (see coq/coq#7109)
- I introduced a kernel check that the internal structure of the branches of a `Case` follows the `Lambda`/`LetIn` structure of the signature of the type of a constructor (see discussions coq/coq#6749 and coq/coq#7068)
- Preparing to the possibility to use `LocalAssum`/`LocalDef` rather than `Lambda`/`LetIn` in the structure of branches of a `Case` (see coq/coq#7080)

Any new comments about continuing in this direction?

**Comment by ppedrot** [comment]
Although I already said that somewhere else, let me repeat here that I am strongly supporting this CEP. What is the expected schedule?

**Comment by herbelin** [comment]
> What is the expected schedule?

I have a version which provides combinators for an abstract version of branches and return clause. This also includes fixes for reductions in `Reductionops`, `Cbv`, `CClosure`. I have a little regression on the proofs produced by `case`/`destruct` (they artificially introduce beta-expansion).

I should probably cut into pieces easier to review: it is currently 19 commits.

So, the schedule is probably this winter.

**Comment by ppedrot** [comment]
FTR, out of procrastination I started working on a direct implementation of the second change, i.e.
```
type ('constr, 'types) pcase_branch =
  ('constr, 'types) Context.Rel.pt * 'constr

type ('constr, 'types) pcase_return =
  ('constr, 'types) Context.Rel.pt * 'types

type ('constr, 'types, 'sort, 'univs) kind_of_term =
  ...
  | Case      of case_info * ('constr, 'types) pcase_return * 'constr * ('constr, 'types) pcase_branch array
  ...
```

I don't know how far @herbelin went, but my take on that is that this second step should just be a temporary one. I suspect that erasing the types from the binders (which are inferable) would yield important efficiency gains, because they account for a important part of the term size. In particular, hashconsing and evar-normalization would probably benefit a lot, and maybe reduction as well. More precisely, I think we should perform the following change:

```
type ('constr, 'types) pcase_branch =
  ('constr, unit) Context.Rel.pt * 'constr

type ('constr, 'types) pcase_return =
  ('constr, unit) Context.Rel.pt * 'types

type 'constr pcase_param = 'constr array

type ('constr, 'types, 'sort, 'univs) kind_of_term =
  ...
  | Case      of case_info * ('constr, 'types) pcase_return * 'constr pcase_param * 'constr * ('constr, 'types) pcase_branch array
  ...
```
where `pcase_param` is the array of parameter of the term being destructed. As of today this information is present in the return clause, but with this encoding scheme recovering it without setting it in the case elimination would require full-blown typing, which might be too costly.

I haven't tried implementing this yet, but it's probably going to be easier after having the second part of this CEP done.

**Comment by SkySkimmer** [comment]
>`('constr, unit) Context.Rel.pt`

Why not (unit, unit)?

**Comment by ppedrot** [comment]
@SkySkimmer You still need the let bodies to compute kernel reduction without calling the environment.

**Comment by herbelin** [comment]
@ppedrot: What I implemented so far is [here](https://github.com/herbelin/github-coq/tree/abstracting-cases). Part of it is ready but with a little regression on the proofs produced by destruction tactics. They introduce useless beta-expansion in the branchse and and I wanted to fix that.

**Comment by ppedrot** [comment]
@herbelin OK, so it seems your set of patches is quite orthogonal to mine. You're dealing with the upper layer changes of behaviour, while I'm just trying to change the kernel representation. If you're not planning on changing the kernel representation, I can rebase mine over yours, if that's not too costly.

**Comment by herbelin** [comment]
> You're dealing with the upper layer changes of behaviour, while I'm just trying to change the kernel representation.

I was progressively abstracting over the type of branches (hence the `type 'a branch = 'a`) so as to eventually be able to change the representation. My methodology was to make `branch` abstract, to make some progress at changing the code where it was relying on the representation, and to remake it concrete so that it compiles with the part of the code which I did not have adapted yet.

> If you're not planning on changing the kernel representation, I can rebase mine over yours, if that's not too costly.

I don't have time and thus concrete plans on this branch before (a minima) February. If you basically agree with the changes already done, feel free to rebase on it and extend it. (I can also do the rebase of the branch over master myself by tonight if ever it would help.)

**Comment by gares** [comment]
I guess the file should be renamed and the pr merged as soon as Coq/coq#13563 is

**Pull request merged**
